#!/bin/sh
git clone https://github.com/Kurento/kurento-jsonrpc-js
git clone https://github.com/Kurento/doc-kurento-readthedocs
git clone https://github.com/Kurento/doc-kurento
git clone https://github.com/Kurento/doc-kurento-room-readthedocs
git clone https://github.com/Kurento/doc-kurento-room
git clone https://github.com/Kurento/kurento-room
git clone https://github.com/Kurento/kurento-module-chroma-bower
git clone https://github.com/Kurento/kurento-module-crowddetector-bower
git clone https://github.com/Kurento/kurento-module-chroma-js
git clone https://github.com/Kurento/kurento-module-crowddetector-js
git clone https://github.com/Kurento/kurento-client-filters-js
git clone https://github.com/Kurento/kurento-module-pointerdetector-bower
git clone https://github.com/Kurento/kurento-module-pointerdetector-js
git clone https://github.com/Kurento/kurento-module-datachannelexample-bower
git clone https://github.com/Kurento/bugtracker
git clone https://github.com/Kurento/gst-plugins-ugly
git clone https://github.com/Kurento/gst-plugins-bad
git clone https://github.com/Kurento/gst-plugins-base
git clone https://github.com/Kurento/kurento-tutorial-node
git clone https://github.com/Kurento/kurento-tutorial-js
git clone https://github.com/Kurento/doc-fiware-readthedocs
git clone https://github.com/Kurento/doc-kurento-repository-readthedocs
git clone https://github.com/Kurento/kurento-tree
git clone https://github.com/Kurento/doc-kurento-tree-readthedocs
git clone https://github.com/Kurento/doc-kurento-jsonrpc-readthedocs
git clone https://github.com/Kurento/doc-kurento-tree
git clone https://github.com/Kurento/doc-kurento-repository
git clone https://github.com/Kurento/doc-kurento-jsonrpc
git clone https://github.com/Kurento/kurento-maven-plugin
git clone https://github.com/Kurento/kurento-module-platedetector-bower
git clone https://github.com/Kurento/kurento-module-datachannelexample-js
git clone https://github.com/Kurento/kurento-module-platedetector-js
git clone https://github.com/Kurento/kms-chroma
git clone https://github.com/Kurento/kms-crowddetector
git clone https://github.com/Kurento/kms-platedetector
git clone https://github.com/Kurento/kms-datachannelexample
git clone https://github.com/Kurento/kms-pointerdetector
git clone https://github.com/Kurento/kms-filters
git clone https://github.com/Kurento/kurento-module-creator
git clone https://github.com/Kurento/kms-jsonrpc
git clone https://github.com/Kurento/kms-cmake-utils
git clone https://github.com/Kurento/kurento-utils-bower
git clone https://github.com/Kurento/libs3
git clone https://github.com/Kurento/libnice
git clone https://github.com/Kurento/openwebrtc-gst-plugins
git clone https://github.com/Kurento/usrsctp
git clone https://github.com/Kurento/jsoncpp
git clone https://github.com/Kurento/kms-plugin-sample
git clone https://github.com/Kurento/kms-opencv-plugin-sample
git clone https://github.com/Kurento/kurento-docker
git clone https://github.com/Kurento/fi-lab-demo
git clone https://github.com/Kurento/apt-transport-s3
git clone https://github.com/Kurento/kurento-module-plumberendpoint-bower
git clone https://github.com/Kurento/kurento-module-plumberendpoint-js
git clone https://github.com/Kurento/promisecallback

